version: "2"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src/public:/src/public
      - ./docker/nginx/app.com.conf:/etc/nginx/conf.d/app.com.conf
    networks:
      - code-network
  app:
    build: ./docker/node
    command: bash -c 'cd src && npm install && npm run debug'
    ports:
     - "3000:3000"
     - "5858:5858"
    volumes :
      - ./src:/src
    networks:
      - code-network
  mongo:
    image: mongo:latest
#    ports:
#     - "27017:27017"
    volumes:
        - ./data:/data/db
    networks:
        - code-network
networks:
  code-network:
      driver: bridge
